version: '3.8'

services:
  mongo:
    image: mongo:6.0
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: tradeinsurance
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - mongo_data:/data/db

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_MONGODB_SERVER: mongo

#  backend:
#    build: ./backend
#    restart: always
#    env_file:
#      - ./backend/.env
#    ports:
#      - "5000:5000"
#    depends_on:
#      - mongo
#
#  frontend:
#    build: ./frontend
#    restart: always
#    env_file:
#      - ./frontend/.env
#    ports:
#      - "3000:3000"
#    depends_on:
#      - backend

volumes:
  mongo_data:
